<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.hundsun.bontal</groupId>
        <artifactId>bontal-biz-service</artifactId>
        <version>1.2.1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>canvas-service</artifactId>
    <packaging>pom</packaging>
    <version>1.0.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <bontal.canvas.version>1.0.0-SNAPSHOT</bontal.canvas.version>
    </properties>

    <modules>
        <module>canvas-api</module>
        <module>canvas-core</module>
        <module>canvas-app</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.hundsun.bontal</groupId>
                <artifactId>canvas-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.hundsun.bontal</groupId>
                <artifactId>canvas-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.hundsun.bontal</groupId>
                <artifactId>base-api</artifactId>
                <version>1.2.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.hundsun.bontal</groupId>
                <artifactId>img-api</artifactId>
                <version>1.2.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.hundsun.bontal</groupId>
                <artifactId>plcy-comm-api</artifactId>
                <version>1.2.0-SNAPSHOT</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
